version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plausible
      - realtime-service

  plausible:
    labels:
      virtual.host: "analytics.newsifier.nl" # change to your domain name
      virtual.port: "8000"
      virtual.tls-email: "kamal@newsifier.com" # change to your email

  realtime-service:
    image: newsifiercom/realtime-service:latest
    restart: always
    labels:
      virtual.host: "realtime-service.newsifier.nl"
      virtual.port: "3000"


volumes:
  caddy-certificates:
    driver: local
